# Generated by Django 4.2.5 on 2023-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='store/categories/')),
                ('No_of_items', models.IntegerField()),
                ('isblocked', models.BooleanField(default=False)),
            ],
        ),
    ]
