# Generated by Django 4.2.5 on 2023-09-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='store/products/')),
                ('image2', models.ImageField(blank=True, upload_to='store/products/')),
                ('image3', models.ImageField(blank=True, upload_to='store/products/')),
                ('image4', models.ImageField(blank=True, upload_to='store/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
