# Generated by Django 4.2.5 on 2023-10-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orders_product_orders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordernumber',
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
            preserve_default=False,
        ),
    ]
