# Generated by Django 4.2.5 on 2023-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_categoryoffer_is_active_productoffer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
